### ISSUE TITLE
Release to CRAN

### ISSUE THREAD

**Issue by russellpierce** [nathanvan/parallelsugar#1]
Any plans to release to CRAN?  Although this solves a Windows-centric problem there is no reason it couldn't run on Linux or MacOS as far as I can tell.  If you pass 'names' as hosts it could even be useful on them as providing a familiar fork-like approach to connecting to SOCK nodes hosted on other machines.

If you don't plan to release to CRAN do you mind if I include mclapply as a private function within a package that I might end up releasing to CRAN?

**Comment by nathanvan** [comment]
I had not planned on it, but I can. I probably won't get to it for a little bit though.

If you wish, feel free to include the code in your package.

**Comment by rorynolan** [comment]
Hi Nathan,
I'd love to see this on CRAN. How would you feel about me forking the repo and then submitting to CRAN on your behalf. I understand if you don't want this, I'd just love to depend upon this package with some of my own packages.
Rory

**Comment by nathanvan** [comment]
Hi Rory,

That would be fine with me. Please, however, list yourself as the
maintainer.

Cheers,

Nathan

**Comment by rorynolan** [comment]
In the end, I decided not to bother, as before I got around to this, some delightful packages for parallel computation appeared on CRAN.
